name: PR-Based Check for Calypso App

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  rollout_dev:
    name: dev
    uses: ./.github/workflows/calypso-deploy.yml
    with:
      HAS_APP_CHANGES: true
      HAS_BFF_CHANGES: true
